---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Other
- type: directory
  path: static/projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: document
  path: static/contact.md
  label: Contact
- type: heading
  label: Front page
- type: document
  path: static/main.md
  label: Main
- type: document
  path: static/about.md
  label: About me
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
