// Libraries
import type { NextPage } from 'next'
import Head from 'next/head'
import parse from 'html-react-parser'
// Styles
import styles from '../styles/FrontPage.module.scss'
// Components
import Nav from '../components/Nav'
import Hr from '../components/Hr'
import Skills from '../components/Skills'

const Home: NextPage = ({ data, about, skills }: any) => {
	const navProps = { text: data.menu_text, first: data.first_name, last: data.last_name }
	return (
		<div>
			<Head>
				<title >Jakub Kapała</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Nav props={navProps} />

			{/* Main section */}
			<main className="flex items-center justify-center px-10 md:gap-10 pt-60 md:pt-48">
				<div className="flex items-center justify-end">
					<img src={data.img_first} height="511px" width="304px" className="aspect-[304/511] md:h-[511px] h-300px" />
				</div>
				<div className="flex items-center justify-start">
					<img src={data.img_second} height="397px" width="491px" className="hidden md:block" />
				</div>
			</main>

			<Hr />

			{/* About us */}
			<section className="grid grid-cols-1 lg:grid-cols-2 gap-24 px-10 md:px-24 mb-12">
				<div className="grid grid-cols-1 gap-y-6 md:gap-y-12 px-0 xl:px-24">
					<h1 className="font-light md:font-thin text-3xl md:text-5xl">{about.title}</h1>
					<div className="font-light md:font-thin text-lg md:text-2xl">{parse(about.post_content)}</div>
					<a href={`mailto:${about.mail}`} className="italic text-xl">{about.footer}<span className="font-medium not-italic">{about.mail}</span></a>
				</div>
				<div className="grid grid-cols-1">
					<div className={styles.hex_container}>
						<div className={`${styles.pentagon} absolute left-0 -bottom-12 bg-kapala-700`}></div>
						<div className={`${styles.pentagon} absolute left-8 bottom-0 bg-kapala-400`}></div>
						<img src="/polygon-border.svg" className={`absolute left-16 bottom-12 w-[280px] aspect-square`} />
						<div className={`${styles.pentagon} block lg:hidden absolute left-16 bottom-12 bg-kapala-300`}></div>

					</div>
				</div>
			</section>

			<Hr flip={true} />
			<Skills data={skills} />
			<Hr />
		</div>
	)
}

// Fetch data from API
export async function getServerSideProps(context: any) {
	const req = { name: "main" }

	const res = await fetch(`http://${context.req.headers.host}/api/single`, { method: 'POST', body: JSON.stringify(req) })
	const data = await res.json()

	req.name = 'about'
	const secondRes = await fetch(`http://${context.req.headers.host}/api/single`, { method: 'POST', body: JSON.stringify(req) })
	const about = await secondRes.json()

	req.name = 'skills'
	const skillsRes = await fetch(`http://${context.req.headers.host}/api/single`, { method: 'POST', body: JSON.stringify(req) })
	const skills = await skillsRes.json()

	return {
		props: { data, about, skills },
	}
}

export default Home
