import type { NextPage } from 'next'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '../styles/FrontPage.module.scss'
import Nav from '../components/Nav'
import Hr from '../components/Hr'

const Home: NextPage = ({ data }: any) => {
	const navProps = { text: data.menu_text, first: data.first_name, last: data.last_name }

	return (
		<div>
			<Head>
				<title >Jakub Kapała</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Nav props={navProps} />

			{/* Main section */}
			<main className="flex items-center justify-center px-10 md:gap-10 pt-60 md:pt-48">
				<div className="flex items-center justify-end">
					<img src={data.img_first} height="511px" width="304px" className="aspect-[304/511] md:h-[511px] h-300px" />
				</div>
				<div className="flex items-center justify-start">
					<img src={data.img_second} height="397px" width="491px" className="hidden md:block" />
				</div>
			</main>

			<Hr />

			{/* About us */}
			<section className="grid grid-cols-1 lg:grid-cols-2 gap-24 px-10 md:px-24 mb-12">
				<div className="grid grid-cols-1 gap-y-12 px-0 xl:px-24">
					<h1 className="font-thin text-2xl md:text-5xl">About me</h1>
					<div className="font-thin text-lg md:text-2xl">I am a software developer, mainly interested
						in web and mobile development. My hobbies
						include cybersecurity, photography, music,
						and widely interpreted technology. I’m based
						in Cracow, Poland.</div>
					<a href="mailto:jakub@kapala.xyz" className="italic text-xl">Feel free to hit me up - <span className="font-medium not-italic">jakub@kapala.xyz</span></a>
				</div>
				<div className="grid grid-cols-1">
					<div className={styles.hex_container}>
						<div className={`${styles.pentagon} absolute left-0 -bottom-12 bg-kapala-700`}></div>
						<div className={`${styles.pentagon} absolute left-8 bottom-0 bg-kapala-400`}></div>
						<img src="/polygon-border.svg" className={`absolute left-16 bottom-12 w-[280px] aspect-square`} />
						<div className={`${styles.pentagon} block lg:hidden absolute left-16 bottom-12 bg-kapala-300`}></div>

					</div>
				</div>
			</section>

			<Hr flip={true} />
		</div>
	)
}

// Fetch data from API
export async function getServerSideProps(context: any) {
	const request = { name: "main" }

	const res = await fetch(`http://${context.req.headers.host}/api/single`, { method: 'POST', body: JSON.stringify(request) })
	const data = await res.json()

	return {
		props: { data },
	}
}

export default Home
