import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = (data) => {
	return (
		<div className={styles.container}>
			<Head>
				<title >Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>{JSON.stringify(data)}</code>
				</p>
			</main>

		</div>
	)
}

export async function getStaticProps() {
	const req = { name: "projects/lorem-ipsum" }

	const res = await fetch(`${process.env.API_URL}/single`, { method: 'POST', body: JSON.stringify(req) })
	const data = await res.json()

	return {
		props: { data },
	}
}

export default Home
