---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: github
  type: text
  config:
    required: false
  label: Github
- name: desc
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: date
  type: datetime
  label: Date
  description: creation date
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: technologies
  type: tag_list
  default: []
  label: Technologies
- name: gallery
  type: image_gallery
  config: {}
  label: Gallery
pages:
- static/projects/lorem-ipsum.md
